### ISSUE TITLE
Ghost travelbox/elevator

### ISSUE THREAD

**Issue by 00c** [Sokomine/travelnet#16]
Travelbox or elevator turn into ghost by delete area with //deleteblocks or other sqlite tools. 
Does not remove or update broken link.

**Comment by Sokomine** [comment]
There have been a lot of changes done in the meantime. Still, travelnets rely on beeing properly removed with the special button in their menu in order to know that a station has been removed. There are fallbacks that update the internal data structure when a station became missing without beeing thus removed, but that's a fallback. There is no way to react to //deleteblocks and similar tools. Please keep in mind that not all blocks are simple ones. Sometimes there are things to do when a block is removed.
