### ISSUE TITLE
Steel Doors (with steelblock texture)

### ISSUE THREAD

**Issue by qwrwed** [Sokomine/travelnet#23]
Doors with a steelblock-like texture would give a modern and opaque alternative to the current glass and stone doors, which would fit in a lot better in some styles of building.

**Comment by Sokomine** [comment]
The "stone" doors are there because their texture looks far more like a typical elevator door to me than the steel block texture in default does.
Anyway: Added a function to register new elevator doors: travelnet.register_door( node_base_name, def_tiles, material_to_craft_from )
Also added  an elevator door made out of tin (not much use for that material elswhere) that uses the clay texture for the door. That's a bit brighter than the stone texture and may work quite well in an environment of steel blocks. If you want other textures, please provide them. The elevator glass door texture may be used as an example.
